/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/event': RouteRecordInfo<'/event', '/event', Record<never, never>, Record<never, never>>,
    '/event_[base64Data]': RouteRecordInfo<'/event_[base64Data]', '/event_:base64Data', { base64Data: ParamValue<true> }, { base64Data: ParamValue<false> }>,
    '/index1': RouteRecordInfo<'/index1', '/index1', Record<never, never>, Record<never, never>>,
  }
}
